--
-- Script was generated by Devart dbForge Studio 2020 for MySQL, Version 9.0.689.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 12/6/2021 11:38:04
-- Server version: 10.4.21
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

DROP DATABASE IF EXISTS pizzéria;

CREATE DATABASE pizzéria
	CHARACTER SET utf8
	COLLATE utf8_hungarian_ci;

--
-- Set default database
--
USE pizzéria;

--
-- Create table `pizzak`
--
CREATE TABLE pizzak (
  ID INT(11) NOT NULL AUTO_INCREMENT,
  nev VARCHAR(100) DEFAULT NULL,
  feltetek TEXT DEFAULT NULL,
  ar INT(11) DEFAULT NULL,
  kep VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (ID)
)
ENGINE = INNODB,
AUTO_INCREMENT = 8,
AVG_ROW_LENGTH = 2340,
CHARACTER SET utf8,
COLLATE utf8_hungarian_ci;

-- 
-- Dumping data for table pizzak
--
INSERT INTO pizzak VALUES
(1, '4 Stagioni vékony pizza', '1/4 articsóka, 1/4 friss gomba, 1/4 prosciutto cotto, 1/4 szalámi, Mozzarella, paradicsom szósz', 1850, '4stagioni.jpg'),
(2, 'Calzone vékony pizza', 'Gomba, Mozzarella, paradicsom szósz, pármai sonka', 1850, 'calzone.jpg'),
(3, 'Capricciosa vékony pizza', 'Gomba, Mozzarella, Paradicsom, articsóka, paradicsom szósz, pármai sonka', 2150, 'capricciosa.jpg'),
(4, 'Margherita vékony pizza', 'Mozzarella, Paradicsom, oregánó, paradicsom szósz', 1650, 'margherita.jpg'),
(5, 'Napoletana vékony pizza', 'Mozzarella, Tonhal, paradicsom szósz', 1850, 'napoletana.jpg'),
(6, 'Quattro Formaggi vékony pizza', 'Parmezán, Rokfort, Trappista, tejfölös alap', 1950, 'quattroformaggi.jpg'),
(7, 'Pugliese vékony pizza', 'Lilahagyma, Mozzarella, paradicsom szósz', 1950, 'pugliese.jpg');

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;