--
-- Script was generated by Devart dbForge Studio for MySQL, Version 7.3.131.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 2020. 01. 30. 6:27:45
-- Server version: 5.5.5-10.1.35-MariaDB
-- Client version: 4.1
--


-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Create database "autosbolt"
--
CREATE DATABASE IF NOT EXISTS autosbolt
	CHARACTER SET utf8
	COLLATE utf8_hungarian_ci;

--
-- Set default database
--
USE autosbolt;

--
-- Drop table "alkatreszek"
--
DROP TABLE IF EXISTS alkatreszek;

--
-- Set default database
--
USE autosbolt;

--
-- Create table "alkatreszek"
--
CREATE TABLE IF NOT EXISTS alkatreszek (
  cikkszam INT(11) NOT NULL AUTO_INCREMENT,
  automarka VARCHAR(50) DEFAULT NULL,
  autotipus VARCHAR(100) DEFAULT NULL,
  kategoria VARCHAR(255) DEFAULT NULL,
  alkatresz_neve VARCHAR(255) DEFAULT NULL,
  netto_ar INT(11) DEFAULT NULL,
  afa INT(11) DEFAULT NULL,
  keszlet INT(11) DEFAULT NULL,
  PRIMARY KEY (cikkszam)
)
ENGINE = INNODB
AUTO_INCREMENT = 12
AVG_ROW_LENGTH = 2048
CHARACTER SET utf8
COLLATE utf8_hungarian_ci;

-- 
-- Dumping data for table alkatreszek
--
INSERT INTO alkatreszek VALUES
(5, 'Skoda', 'Fabia', 'Motor', 'Olaj (1L)', 1500, 18, 5),
(6, 'Skoda', 'Fabia', 'Motor', 'Olaj (5L)', 6500, 18, 2),
(7, 'Skoda', 'Fabia', 'Karosszéria', 'Bal első tükör', 20000, 27, 1),
(8, 'Opel', 'Agila', 'Karosszéria', 'Hátsó lökhárító', 14800, 27, 1),
(9, 'Skoda', 'Octavia', 'Elektronika', 'Központi vezérlőegység', 500000, 18, 0),
(10, 'Trabant', 'limuzin', 'Hajtás', 'gumi', 12500, 27, 5),
(11, 'Honda', 'CR-V', 'Villamossági rendszer', 'izzó', 1000, 27, 100);
-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
