--
-- Script was generated by Devart dbForge Studio 2020 for MySQL, Version 9.0.791.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 1/26/2022 11:59:16
-- Server version: 10.4.21
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

DROP DATABASE IF EXISTS debrecen;

CREATE DATABASE debrecen
	CHARACTER SET utf8
	COLLATE utf8_hungarian_ci;

--
-- Set default database
--
USE debrecen;

--
-- Create table `kartyak`
--
CREATE TABLE kartyak (
  kategoria VARCHAR(255) DEFAULT NULL,
  kep VARCHAR(255) DEFAULT NULL,
  kephover VARCHAR(255) DEFAULT NULL,
  easteregg VARCHAR(255) DEFAULT NULL,
  rovidleiras TEXT DEFAULT NULL,
  webpage VARCHAR(255) DEFAULT NULL
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 6553,
CHARACTER SET utf8,
COLLATE utf8_hungarian_ci;

-- 
-- Dumping data for table kartyak
--
INSERT INTO kartyak VALUES
('Tömegközlekedés', 'villamos.jpg', 'villamos_regi.jpg', 'villamos_torot.jpg', 'Bár Debrecenben kényelmes sétával minden fontos látnivaló és helyszín könnyen elérhető, aki mégsem a sétát választaná, annak a helyi tömegközlekedés számos kényelmes lehetőséget kínál. Két villamos-, öt trolibusz- és több, mint ötven autóbuszvonalon történik menetrend szerinti utasszállítás Debrecenben, de a város biztonságos kerékpárút-hálózaton akár két keréken is felfedezhető.', 'https://www.dkv.hu/'),
('Egyetem', 'zegyetem.jpg', 'zegytem_regi.jpg', 'zegytem_regi.jpg', 'A Debreceni Egyetem – mely az ország legrégebbi, folyamatosan működő felsőoktatási intézményei közé tartozik – egyike Magyarország kiemelt kutatóegyetemeinek, amely közel 30 ezer hallgatóval és 1500 oktatóval, 15 karával, 25 doktori iskolájával a legszélesebb hazai képzési kínálatot nyújtja.', 'https://unideb.hu/'),
('Nagytemplom\r\n', 'nagytemplom.jpg', 'nagytemplom_regi.jpg', 'nagytemplom_regi.jpg', 'Debrecen jelképe, az ország legnagyobb református temploma. 1849. április 14-én Kossuth Lajos itt olvasta fel a Függetlenségi Nyilatkozatot. Az épület mai formáját és klasszicista stílusát a Péchy Mihály és Thaler József tervei alapján 1819 és 1823 között zajló építkezéskor kapta, miután 1802-ben a korábbi templom leégett. Jakob Deutschmann bécsi mester készítette a templomi orgonát, ami többszöri átalakítás után jelenleg az ország második legnagyobb mechanikus orgonája. A templom tornyaiból és a timpanon mögötti acélhídról csodálatos kilátás nyílik a városra. Útban felfelé megtekinthető az 56 mázsás Rákóczi-harang. Az egyházi eseményeken túl a templomban egyháztörténeti kiállítások, orgonakoncertek és zenei rendezvények várják a látogatókat. 2013 óta nemzeti emlékhely.', 'https://www.nagytemplom.hu/'),
('Aquatikum\r\n', 'csuszoda.jpg', 'csuszoda_regi.jpg', 'csuszoda_regi.jpg', 'A régi Nagyerdei strandfürdő átalakításának koncepciója az volt, hogy nem elég a modern élményelemek és medencék elhelyezése, hanem kell valami, ami ikonikus jelként egyértelműen Debrecenhez és a Nagyerdőhöz kapcsolódva közvetíti a vizes parkerdei élményeket. Ennek szellemében tervezték meg az új strandfürdőt, melyben a hullámzó vízfelületek, a vízesések, a növényfalak és a vízfátyolok fogják össze és teszik folyton változó, csillogó, az erdő fáit visszatükröződő élményközponttá a komplexumot.', 'https://www.aquaticum.hu/hu'),
('Stadion', 'megintegystadion.jpg', 'megintegystadion_regi.jpg', 'megintegystadion_regi.jpg', 'Debrecen hétszeres magyar bajnok futballcsapata – a Loki – 2014-ben új otthont kapott. A különleges és modern építészeti megoldásokkal épült Nagyerdei Stadion Magyarország egyik legkorszerűbb arénája.A stadion a magas fák ölelésében szinte észrevétlenül olvad bele a természeti környezetbe. A 20 000 férőhelyes multifunkcionális létesítmény nem csak sportversenyek, edzések, de kulturális rendezvények befogadására is kiválóan alkalmas.', 'https://nagyerdeistadion.hu/home');

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;