--
-- Script was generated by Devart dbForge Studio 2020 for MySQL, Version 9.0.791.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 1/18/2022 22:26:41
-- Server version: 10.4.21
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

DROP DATABASE IF EXISTS menükreátor;

CREATE DATABASE menükreátor
	CHARACTER SET utf8
	COLLATE utf8_hungarian_ci;

--
-- Set default database
--
USE menükreátor;

--
-- Create table `menu`
--
CREATE TABLE menu (
  id INT(11) NOT NULL AUTO_INCREMENT,
  het INT(11) DEFAULT NULL,
  nap INT(11) DEFAULT NULL,
  leves VARCHAR(255) DEFAULT NULL,
  foetel VARCHAR(255) DEFAULT NULL,
  desszert VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 297,
AVG_ROW_LENGTH = 655,
CHARACTER SET utf8,
COLLATE utf8_hungarian_ci;

--
-- Create table `etelek`
--
CREATE TABLE etelek (
  id INT(11) NOT NULL AUTO_INCREMENT,
  etel VARCHAR(255) DEFAULT NULL,
  kategoria INT(11) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 59,
AVG_ROW_LENGTH = 282,
CHARACTER SET utf8,
COLLATE utf8_hungarian_ci;

-- 
-- Dumping data for table menu
--
INSERT INTO menu VALUES
(272, 6, 1, 'Eperkrémleves', 'Sertés terrine', 'Fagylaltkehely'),
(273, 6, 2, 'Tojásleves', 'Sertéscsülök pékné módra', 'Tiramisu'),
(274, 6, 3, 'Gulyásleves', 'Szedervölgyi pulykamell', 'Rákóczi túrós'),
(275, 6, 4, 'Húsleves', 'Sertés sárgadinnyével', 'Tiramisu'),
(276, 6, 5, 'Gulyásleves', 'Sertés szelet sajtmártással', 'Madártej'),
(277, 1, 1, 'Erőleves tojással', 'Rántott karajszelet', 'Dobos torta'),
(278, 1, 2, 'Hagymakrémleves', 'Vasalt csirkemell salátával', 'Sacher torta'),
(279, 1, 3, 'Gyümölcsleves', 'Csirkepaprikás', 'Holland krémes'),
(280, 1, 4, 'Jókai bableves', 'Nosztalgia csirkemell', 'Holland krémes'),
(281, 1, 5, 'Eperkrémleves', 'Barbár csirke', 'Somlói galuska'),
(282, 8, 1, 'Húsleves', 'Brassói aprópecsenye', 'Sacher torta'),
(283, 8, 2, 'Orjaleves', 'Velővel töltött cannelloni', 'Gundel palacsinta'),
(284, 8, 3, 'Hagymakrémleves', 'Nosztalgia csirkemell', 'Rákóczi túrós'),
(285, 8, 4, 'Hagymakrémleves', 'Nosztalgia csirkemell', 'Dobos torta'),
(286, 8, 5, 'Erőleves tojással', 'Nosztalgia csirkemell', 'Gundel palacsinta'),
(287, 20, 1, 'Húsleves', 'Egész Süllő', 'Gundel palacsinta'),
(288, 20, 2, 'Húsleves', 'Padlizsános lasagne', 'Mézes zserbó'),
(289, 20, 3, 'Jókai bableves', 'Sertés sárgadinnyével', 'Fagylaltkehely'),
(290, 20, 4, 'Erőleves tojással', 'Egész Süllő', 'Dobos torta'),
(291, 20, 5, 'Paradicsomleves', 'Brassói aprópecsenye', 'Madártej'),
(292, 25, 1, 'Orjaleves', 'Pisztráng egészben sütve', 'Tiramisu'),
(293, 25, 2, 'Tojásleves', 'Hawaii csirkemell', 'Gesztenypüré tejszínhabbal'),
(294, 25, 3, 'Karfiol leves', 'Rántott karajszelet', 'Nosztalgia krémes'),
(295, 25, 4, 'Tárkonyos raguleves', 'Pasta all', 'Fagylaltkehely'),
(296, 25, 5, 'Gyümölcsleves', 'Szedervölgyi pulykamell', 'Gundel palacsinta');

-- 
-- Dumping data for table etelek
--
INSERT INTO etelek VALUES
(1, 'Erőleves tojással', 1),
(2, 'Húsleves', 1),
(3, 'Orjaleves', 1),
(4, 'Gulyásleves', 1),
(5, 'Jókai bableves', 1),
(6, 'Tárkonyos raguleves', 1),
(7, 'Hagymakrémleves', 1),
(8, 'Eperkrémleves', 1),
(9, 'Paradicsomleves', 1),
(10, 'Tojásleves', 1),
(11, 'Gyümölcsleves', 1),
(12, 'Brokkolikrémlves', 1),
(13, 'Karfiol leves', 1),
(14, 'Parajos gnocci sajttal', 2),
(15, 'Milánói makaróni', 2),
(16, 'Padlizsános lasagne', 2),
(17, 'Pasta all''aradiata', 2),
(18, 'Barátfüle', 2),
(19, 'Házi túrós csusza', 2),
(20, 'Ricottás-spenótos tortellini', 2),
(21, 'Velővel töltött cannelloni', 2),
(22, 'Kijevi jércemell', 2),
(23, 'Hawaii csirkemell', 2),
(24, 'Vasalt csirkemell salátával', 2),
(25, 'Szedervölgyi pulykamell', 2),
(26, 'Nosztalgia csirkemell', 2),
(27, 'Csirkepaprikás', 2),
(28, 'Barbár csirke', 2),
(29, 'Spenótos csirke', 2),
(30, 'Tejfölös csirkeragu', 2),
(31, 'Süllő filé roston', 2),
(32, 'Vasi harcsaszelet', 2),
(33, 'Egész Süllő', 2),
(34, 'Pisztráng egészben sütve', 2),
(35, 'Haltorta tócsnival', 2),
(36, 'Milánói borda', 2),
(37, 'Betyár borda', 2),
(38, 'Cigánypecsenye', 2),
(39, 'Brassói aprópecsenye', 2),
(40, 'Sertéscsülök pékné módra', 2),
(41, 'Rántott karajszelet', 2),
(42, 'Sertés Cordon Bleu', 2),
(43, 'Sertés sárgadinnyével', 2),
(44, 'Szecsuáni sertés', 2),
(45, 'Sertés szelet sajtmártással', 2),
(46, 'Sertés terrine', 2),
(47, 'Madártej', 3),
(48, 'Gundel palacsinta', 3),
(49, 'Fagylaltkehely', 3),
(50, 'Sacher torta', 3),
(51, 'Somlói galuska', 3),
(52, 'Dobos torta', 3),
(53, 'Mézes zserbó', 3),
(54, 'Tiramisu', 3),
(55, 'Gesztenypüré tejszínhabbal', 3),
(56, 'Rákóczi túrós', 3),
(57, 'Nosztalgia krémes', 3),
(58, 'Holland krémes', 3);

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;